######### DETAILS OF PLAYBOOK #########
# Playbook Name: generate_report.yml
# Playbook Description: To generate a HTML report based on input row value, column value, row delimiter, column delimiter, report name.
# Inputs Required: column_values, row_values, row_value_delimiter, column_delimiter, report_name, html_file_path
## Sample values ##
  # column_values: "ServerName;Reachable;serverType;osVersion;Uptime;cpuUsagePercent;cpuCores"
  # row_values: "localhost;Yes;Physical;Microsoft Windows 10 Pro;4D 6H 57M 48S;<td bgcolor=greenColor>13</td>;<td bgcolor=yellowColor>4</td>~abc;No;-;-;-;-;-~xyz;No;-;-;-;-;-"
  # row_value_delimiter: "~"
  # column_delimiter: ";"
  # report_name: "PreCheck"
  # html_file_path: "/home/ec2-user/testing/output"
## COMMAND TO EXECUTE BY PASSING VALUES AT RUN TIME ##
# ansible-playbook -e "column_values=ServerName;Reachable;serverType;osVersion;Uptime;cpuUsagePercent;cpuCores, row_values=localhost;Yes;Physical;Microsoft Windows 10 Pro;4D 6H 57M 48S;<td bgcolor=greenColor>13</td>;<td bgcolor=yellowColor>4</td>~abc;No;-;-;-;-;-~xyz;No;-;-;-;-;-, row_value_delimiter=~, column_delimiter=;, report_name=PreCheck, html_file_path=./output" generate_report.yml
---
- name: Generate HTML Report
  hosts: localhost
  gather_facts: true

  vars:
    ## BELOW VALUES ARE HARDCODED FOR TESTING. PUT '#' FROM LINE 21 TO 26 IF INPUTS TO BE TAKEN AT RUN TIME ##
    column_values: "ServerName;Reachable;serverType;osVersion;Uptime;cpuUsagePercent;cpuCores"
    row_values: "localhost;Yes;Physical;Microsoft Windows 10 Pro;4D 6H 57M 48S;<td bgcolor=greenColor>13</td>;<td bgcolor=yellowColor>4</td>~abc;No;-;-;-;-;-~xyz;No;-;-;-;-;-"
    row_value_delimiter: "~"
    column_delimiter: ";"
    report_name: "PreCheck"
    html_file_path: "./output"

    ## REMOVE THE '#' IF INPUTS TO BE TAKEN AT RUN TIME. ##
    # column_values: "{{ column_values }}"
    # row_values: "{{ row_values }}"
    # row_value_delimiter: "{{ row_value_delimiter }}"
    # column_delimiter: "{{ column_delimiter }}"
    # report_name: "{{ report_name }}"
    # html_file_path: "{{ html_file_path }}"
    
  tasks:
  
    - name: Parse JSON response
      set_fact:
        report_file_name: "{{ report_name }}-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}-{{ ansible_date_time.second }}"

    - name: show report name
      debug:
        var: report_file_name

    - name: Parse JSON response
      set_fact:
        report_path: "{{ html_file_path }}/{{ report_file_name }}.html"

    - name: Create HTML report file
      template:
        src: report_template2.j2
        dest: "{{ report_path }}"

